title: "jekyll-import • Import your old &amp; busted site to Jekyll"
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
repository: https://github.com/jekyll/jekyll-import
latest_release: 0.10.0

collections:
  docs:
    output: true
  importers:
    output: true

theme: jekyll-theme-minimal